### ISSUE TITLE
JIP SLs do not have BFT marks :(

### ISSUE THREAD

**Issue by AChesheireCat** [BourbonWarfare/POTATO#541]
If possible, could we add a way for JIP SLs to create a BFT mark? Or grab an existing one, ala if ASL crashes out, they JIP and grab the vacant mark?

**Comment by kil0byt3** [comment]
I wanted to feel included

**Comment by kil0byt3** [comment]
I assigned myself because I wanted to feel included

discussion of possible sltns was here: https://discord.com/channels/204621032428929025/285870164153597953/1282538469654007920

**Comment by lambdatiger** [comment]
Struggling to recreate this, let me know if we can pin down what exact steps are needed to make this happen

**Comment by AChesheireCat** [comment]
Per Alablm's comment in the #scripting channel on discord (https://discord.com/channels/204621032428929025/285870164153597953/1285250244744974366) - feature request: add feature/button that allows staff to assign a BFT mark through the admin tools

**Comment by lambdatiger** [comment]
Issue comes down to the marker being tied to the SL rather than the group in BWMF. For example, this Squad Leader has the ASL mark instead of the mark being tied to the squad.
![image](https://github.com/user-attachments/assets/7228f4eb-6fa7-44e3-bde9-bc861d11035b)

I would suggest closing the issue, creating an issue on BWMF, and moving feature requests to a separate issue
